# render.yaml
services:
  - type: web
    name: idp-dashboard
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://santoshkamal:San_2006@cluster0.yoeuyut.mongodb.net/idp?retryWrites=true&w=majority&appName=Cluster0
